import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { connectMetamask, checkMetamaskConnected } from '../functions/metamask'

export default function Home() {
	const router = useRouter()

	async function handleConnection() {
		let currAccount = await connectMetamask()
		if (currAccount) {
			router.push('MainArea')
		}
	}

	useEffect(() => {
		async function startUp() {
			let currAccount = await connectMetamask()
			if (currAccount) {
				router.push('MainArea')
			}
		}
		startUp()
	}, [])

	return (
		<div>
			<Head>
				<title>CrypChip</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className=' flex items-center justify-center h-[100vh]'>
				<button className='btn btn-primary' onClick={handleConnection}>
					Connect Wallet
				</button>
			</div>
		</div>
	)
}
