import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { connectMetamask, checkMetamaskConnected } from '../functions/metamask'

export default function Home() {
	const router = useRouter()

	async function handleConnection() {
		let currAccount = await connectMetamask()
		if (currAccount) {
			router.push('MainArea')
		}
	}

	useEffect(() => {
		async function startUp() {
			let currAccount = await connectMetamask()
			if (currAccount) {
				router.push('MainArea')
			}
		}
		// startUp()
	}, [])

	return (
		<div>
			<Head>
				<title>CrypChip</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<style>
				{
					'body { background: linear-gradient(110deg, #3bd0fd 60%, #090801 60%); }'
				}
			</style>
			<div className=' flex flex-col items-center justify-center h-[100vh] space-y-16 text-transparent bg-clip-text bg-gradient-to-br from-red-400 to-sky-600'>
				<div className='text-9xl'>CrypChip</div>
				<button className='btn btn-primary' onClick={handleConnection}>
					Connect Wallet
				</button>
			</div>
		</div>
	)
}
